### ISSUE TITLE
Add an option to remove common indentation from a block.

### ISSUE THREAD

**Issue by jszakmeister** [chrisbra/NrrwRgn#19]
It'd be really nice if there was an option in NrrwRgn to help remove common indentation from the block being narrowed, and insert it back when finished.  It would help editing embedded documents, such as code buried in Sphinx code blocks, and other formats where the indentation is normally not welcome.

**Comment by agguser** [comment]
This "removing common indents" is especially useful when folding levels are more than `foldnestmax`, which is limited to 20. Here is my try:

```vim
fu! s:Nind() range   " adjust indents on buffer's (new) narrowed windows
   for l in range(a:firstline, a:lastline)
      let ind = matchstr(getline(l), "^\\s*")
      if l == a:firstline | let ind_min = ind
      elseif ind < ind_min | let ind_min = ind | endif | endfor
   let b:nrrw_aucmd_create = 'sil %s/^'.ind_min.'// | setl nomodified'
   let b:nrrw_aucmd_close = 'sil %s/^/'.ind_min.'/'
   endf
com! -range Nind <line1>,<line2>call s:Nind() | <line1>,<line2>NR!
map ,n :Nind<CR>
```
