### ISSUE TITLE
General Problems

### ISSUE THREAD

**Issue by orbisvicis** [chrisbra/NrrwRgn#35]
Just installed with vundle, but the installation's *default* behaviour differs from that of the screencast:

1] Narrow Region: `<Leader>nr`, `:NR`:

Original buffer split is maximized, narrowed region split is shrunk-fit to contents.

2] Widen region:
 * `:WidenRegion`, `:w`: narrowed window buffer is opened (duplicated) in what used to be the original contents buffer.
 * `wq`: original window split updated to contain narrowed window buffer; narrowed window buffer/split wiped & closed.

**Comment by chrisbra** [comment]
Am 2015-02-19 05:24, schrieb Yclept Nemo:
> Just installed with vundle, but the installation's _default_ behaviour
> differs from that of the screencast:
> 
> 1] Narrow Region: <Leader>nr, :NR:
> 
> Original buffer is maximized, narrowed region is shrink-fit to
> contents

I am not sure, I understand the problem.
The default split size is 20. This can be adjusted by setting the 
g:nrrw_rgn_wdth variable
(see :h NrrwRgn-config)

> 
> 2] Widen region:
> 
>  	* :WidenRegion, :w: narrowed window buffer is opened (duplicated) in
> what used to be the original contents buffer

The narrowed window will stay open. That is intended.

>  	* wq: original window split updated to contain narrowed window
> buffer; narrowed window buffer/split wiped & closed.


Yes that is expected. What is the problem with this approach?

Best,
Christian

**Comment by orbisvicis** [comment]
>> The default split size is 20. This can be adjusted by setting the g:nrrw_rgn_wdth variable

Right, I am mistaken on this. Nonetheless I think it would be nice for the narrow region to automatically fit the narrow text, up to a percentage of the total height, say 80%. Consider it a feature request?

Regarding the actual problem, I think some pictures would help illustrate:

Before:
![split-before](https://cloud.githubusercontent.com/assets/730739/6289736/3b2f7b4e-b8f0-11e4-8ac9-fc06f75ac77f.png)

After `:w`
![split-w](https://cloud.githubusercontent.com/assets/730739/6289737/3b436b2c-b8f0-11e4-9467-27a27bcde171.png)

Or after `:wq`
![split-wq](https://cloud.githubusercontent.com/assets/730739/6289738/3b4bf562-b8f0-11e4-91e5-cafd139f7cab.png)

**Comment by chrisbra** [comment]
Hi Yclept!

On Fr, 20 Feb 2015, Yclept Nemo wrote:

> >> The default split size is 20. This can be adjusted by setting the g:nrrw_rgn_wdth variable
> 
> Right, I am mistaken on this. Nonetheless I think it would be nice for the narrow region to automatically fit the narrow text, up to a percentage of the total height, say 80%. Consider it a feature request?

I just committed a change, that makes the window smaller, if 20 lines is 
too much. Does that help you?

> Regarding the actual problem, I think some pictures would help illustrate:
> 
> Before:
> ![split-before](https://cloud.githubusercontent.com/assets/730739/6289736/3b2f7b4e-b8f0-11e4-8ac9-fc06f75ac77f.png)
> 
> After `:w`
> ![split-w](https://cloud.githubusercontent.com/assets/730739/6289737/3b436b2c-b8f0-11e4-9467-27a27bcde171.png)
> 
> Or after `:wq`
> ![split-wq](https://cloud.githubusercontent.com/assets/730739/6289738/3b4bf562-b8f0-11e4-91e5-cafd139f7cab.png)

The viewpoint in the original window changes? I do not see this here.
What system are you using?

Best,
Christian
-- 
Den Gebenden schmückt, was den Empfangenden beglückt.
		-- Al-Hariri

**Comment by chrisbra** [comment]
Hm, looking at your screenshot again, this looks like both windows display the narrowed window and no window displays the original buffer after the :w or :wq. Is this what is happening? That is clearly a bug. How did you do that?

**Comment by orbisvicis** [comment]
> How did you do that?

Heh, I was wondering that... Actually, I've narrowed it down to this `~/.vimrc` setting:
```
set hidden
```

Unfortunately after commenting that setting out (ie, `set nohidden`), during testing I can trigger the following error on new, unsaved buffers.
```
4 more lines
Error detected while processing function <SNR>24_WriteNrrwRgn..nrrwrgn#WidenRegion:
line  136:
E37: No write since last change (add ! to override)
Press ENTER or type command to continue
```

> I just committed a change, that makes the window smaller, if 20 lines is too much. Does that help you?

I haven't tested, but it sounds like the exact opposite: I would like the narrow region window to expand to fit the "focused" text (up to a certain limit).

**Comment by chrisbra** [comment]
I think I have fixed the :set hidden issue. Please check again.

**Comment by orbisvicis** [comment]
Yes, it is fixed! Thank you.

**Comment by chrisbra** [comment]
Okay, then I close this.
