### ISSUE TITLE
E117: Unknown function: <SNR>273_GoToWindow

### ISSUE THREAD

**Issue by adelarsq** [chrisbra/NrrwRgn#42]
After the last update when pressing ```:q<CR>``` in the NrrwRgn window shows an error:

![erro1](https://cloud.githubusercontent.com/assets/430272/6845947/82076dde-d398-11e4-9316-3faa4a110ce6.png)

**Comment by chrisbra** [comment]
Am 2015-03-26 13:16, schrieb Adelar da Silva Queiróz:
> After the last update when pressing :q<CR> in the NrrwRgn window shows
> an error:

Thanks. Shoot I missed something in the merge. I'll fix it soon. Until 
then, please proceed with the last version.


Best,
Christian

**Comment by chrisbra** [comment]
Can you please update and check again? Thanks

**Comment by adelarsq** [comment]
Thanks. It's working. The message does not appear anymore. I'm using with [minibufexpl](https://github.com/techlivezheng/vim-plugin-minibufexpl). The only remaining problem is that the focus still stays in minibufexpl window when exits.

**Comment by chrisbra** [comment]
Please explain more clearly what you have done, what you expect and what happened and how did it work before. Thanks

**Comment by adelarsq** [comment]
Let's see. In this case I'm editing two lines:

![image](https://cloud.githubusercontent.com/assets/430272/6881205/1dc32c12-d534-11e4-971d-a5bec0ab3721.png)
After to press ```:q<CR>``` on the NarrowRgn window the cursor goes to MiniBufExplorer window and not to the original:

![image](https://cloud.githubusercontent.com/assets/430272/6881220/9c8445a4-d534-11e4-9bcd-b58e157b49b1.png)
Until the df14d71 commit was working fine.

**Comment by chrisbra** [comment]
Thanks, I could reproduce it. Should be fixed now.

**Comment by adelarsq** [comment]
It's working :+1:
