### ISSUE TITLE
:NR! not sync after switching back to original buffer

### ISSUE THREAD

**Issue by agguser** [chrisbra/NrrwRgn#44]
After using `:NR!` to open narrow buffer in current window, if you switch back to original buffer (`:b#`) and then switch back again (`:b#`) to narrow buffer, then modify and save (`:w`), then "E676: No matching autocommands for acwrite buffer" error occurs.

**Comment by chrisbra** [comment]
Okay, that was tricky. Please check.

**Comment by agguser** [comment]
When saving narrow buffer for second time, I get "NarrowRegion: Error writing changes back,Narrowed Window invalid!" error.

**Comment by chrisbra** [comment]
please check again

**Comment by agguser** [comment]
Thanks for fixing it.
