### ISSUE TITLE
After closing a narrow region buffer the original section is strangely selected.

### ISSUE THREAD

**Issue by Serabe** [chrisbra/NrrwRgn#45]
After selecting a part of my code (starting on line 270), editing the narrow region and closing it, it gets somehow higlighted.

In the image, usual text looks like the top part, normal visual selection looks like the selection up to line 268 and a narrow region closed looks like the rest of the code.
![code](https://cloud.githubusercontent.com/assets/36221/8640220/060f6cd2-28f1-11e5-96e1-f7d2b90a8bfc.png)

**Comment by chrisbra** [comment]
That is a problem, that has come up every now and then. I tried to fix it in the past several times, but it seems to reappear. As a start, can you give me the commands to start and end the narrowed window?

As a workaround you can remove the highlighting manually by using `:call clearmatches()`

**Comment by Serabe** [comment]
I start it with `:nr` and a visual selection and close it with `:wq`

**Comment by chrisbra** [comment]
should be fixed now

**Comment by Serabe** [comment]
Works so far. Thank you!
