### ISSUE TITLE
mapping already exists for ,nr

### ISSUE THREAD

**Issue by digitalronin** [chrisbra/NrrwRgn#52]
Hi there

Thanks for a great plugin.

Is there any chance you could include the same kind of fix you made to improvedft to stop the plugin from stomping on existing mappings?

    https://github.com/chrisbra/improvedft/issues/4

Kind regards

David

**Comment by chrisbra** [comment]
Am 2015-12-03 12:52, schrieb David Salgado:
> Hi there
> 
> Thanks for a great plugin.
> 
> Is there any chance you could include the same kind of fix you made to
> improvedft to stop the plugin from stomping on existing mappings?
> 
> https://github.com/chrisbra/improvedft/issues/4
> 
> Kind regards
> 
> David

So you don't want the ,nr map? Or should NrrwRgn overwrite that mapping?

Best,
Christian

**Comment by digitalronin** [comment]
Hi Christian
Sorry, I didn't see your reply, yesterday.
The change you made is exactly what I was asking for. Thanks so much.
David
