### ISSUE TITLE
Feature request: text-object

### ISSUE THREAD

**Issue by Alok** [chrisbra/NrrwRgn#56]
For the moment, let `N` be the mapping for *narrow* even though that would be a bad mapping.

Then you could do things like:

```vim
Nip " narrow a paragraph
N$ " narrow line
Nii "narrow indented region
```

**Comment by chrisbra** [comment]
Am 2016-11-14 02:00, schrieb Alok Singh:
> For the moment, let N be the mapping for _narrow_ even though that
> would be a bad mapping.
> 
> Then you could do things like:
> 
> Nip " narrow a paragraph
> N$ " narrow line
> Nii "narrow indented region
> 

You mean like what in the manual is described here:
https://github.com/chrisbra/NrrwRgn/blob/master/doc/NarrowRegion.txt#L151-L152

**Comment by Alok** [comment]
And that's what I get for not RTFM.
