### ISSUE TITLE
Error when writing narrowed region

### ISSUE THREAD

**Issue by edgimar** [chrisbra/NrrwRgn#60]
I've encountered an error when trying to write/save a narrowed region.  These are the steps I followed to get the error:

1. open two different python files, `A.py` and `B.py`  Everything below here is done w/ `B.py` or a narrowed buffer from it.
2. collapse all folds in `B.py`
3. unfold ClassOne, place cursor on (folded) MethodOne line, and run `:NR`
4. place cursor on (folded) ClassTwo, and run `:NR!`
5. make change to the narrowed ClassTwo buffer
6. run `:w` and the following error occurs:

```
Error detected while processing function <SNR>65_WriteNrrwRgn[14]..nrrwrgn#WidenRegion[182]..<SNR>65_RecalculateLineNumbers:
line    9:
E730: using List as a String
E15: Invalid expression: s:nrrw_rgn_lines[instn].start[1] <= s:nrrw_rgn_lines[a:instn].start[1]
```

After dismissing this error, the source buffer (`B.py`) replaces the narrowed buffer, and does appear to be updated correctly, however the syntax highlighting is turned off (was previously on).

The foldmethod is set to `expr` and I'm using the GetPythonFold() function from the jpythonfold plugin at http://www.vim.org/scripts/script.php?script_id=2527, in case that's relevant.

**Comment by edgimar** [comment]
I think I have fixed the error, but **the losing of syntax highlighting still persists**.  The error in my case was due to having the following code in my .vimrc:

```
autocmd BufWinLeave *
    \   if expand('%') != '' && &buftype !~ 'nofile'
    \|      mkview!
    \|  endif
autocmd BufWinEnter *
    \   if expand('%') != '' && &buftype !~ 'nofile'
    \|      silent loadview
    \|  endif
```

To fix it, I needed to add `&& @% !~ 'NrrwRgn'` to the if-statement conditions.

So, any ideas on how to solve the vanishing syntax highlighting issue?

**Comment by chrisbra** [comment]
When does the syntax highlight goes off?

**Comment by chrisbra** [comment]
You should probably change your vimrc snippet to something like
```
autocmd BufWinLeave *
    \   if expand('%') != '' && empty(&buftype)
    \|      mkview!
    \|  endif
autocmd BufWinEnter *
    \   if expand('%') != '' && empty(&buftype)
    \|      silent loadview
    \|  endif
```
