### ISSUE TITLE
After  `:wq`, the cusor didn't go back the origin window

### ISSUE THREAD

**Issue by weaming** [chrisbra/NrrwRgn#70]
It go into the first window which is not expected.

**Comment by chrisbra** [comment]
So were did it go?

**Comment by chrisbra** [comment]
please provide a complete example and mention exactly what you expect and what happened instead. Thanks.

**Comment by weaming** [comment]
Steps:
1. select text
2. call `NRV`
3. edit selected text in new split window
4. `:wq`
5. origin text replace and cursor go into the first window except the temp window, if exist multiple windows, cursor will go into another window, this behavior is not expected. What I expect is it go back into the window contains the origin text.

**Comment by chrisbra** [comment]
Well, Works for me. I cannot reproduce and you didn't say where the temp windows come from. Might be another plugin interfering. So please try to come up with a reproducible example.

**Comment by weaming** [comment]
There are 2 windows, one is the `NERDTree` plugin on the left, another one is the normal buffer window on the right. 

Select text in buffer window, then edit in new window opened by `:NRV` on the top. After `:wq`, cursor jump into the `NERDTree` window...
