### ISSUE TITLE
preserve foldmethod used by FastFold

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/NrrwRgn#75]
[FastFold](https://github.com/Konfekt/FastFold) speeds up folding by setting the fold method to `manual` by default and only changing it to the original foldmethod when folds are recomputed by storing the original foldmethod in a variable `b:lastfdm`. Could NrrwRgn copy the `b:lastfdm` into the newly created `NrrwRgn_...` buffer for compatibility with FastFold?

**Comment by Konfekt** [comment]
Yes, by adding to your `vimrc` the line

```vim
autocmd BufWinEnter * let b:nrrw_aucmd_create = "let w:lastfdm = getwinvar(winnr('#'), 'lastfdm')"
```

**Comment by chrisbra** [comment]
wait a second, perhaps NrrwRgn can do this automatically?

**Comment by Konfekt** [comment]
Not sure how. But there may be buffer and window-local variables, set by plug-ins, that NrrwRgn does not know about explicitly. Perhaps one could copy all of them, but then this is probably even less desirable than handpicking those that should be transferred.
