### ISSUE TITLE
Docs fix

### ISSUE THREAD

**Issue by zdm** [chrisbra/NrrwRgn#77]
Please, fix this error:
```
 Vim(helptags):E154: Duplicate tag "b:nrrw_aucmd_close" in file C:\Users\zdm\.vim\bundle\.cache\.vimrc\.dein\doc/NarrowRegion.txt
```

**Comment by chrisbra** [comment]
thanks,
should be fixed now

**Comment by zdm** [comment]
I am sorry, but error is still present.

**Comment by chrisbra** [comment]
There are exactly two mentions of `b:nrrw_aucmd_close` in the help file now, and only one of that is a tag. So I don't know why you would still see this error.
Have you updated the plugin? I also see this strange cache from dein, have you tried to clear it?

**Comment by zdm** [comment]
Yes, I cleared cache.
Still see this.

**Comment by chrisbra** [comment]
ah, it was another duplicate tag. Please always show the complete error. Anyhow, should be fixed now.
